### ISSUE TITLE
Sharing link only half working

### ISSUE THREAD

**Issue by emunaelator** [realvorl/BadgeSVGen#2]
While choosing to share a badge, I could verify that the Base64 data is correct, the link does not go back to the app, but instead to your @realvorl main or profile repo ( ignoring the /BadgeSVGen path)

I think this is a bug.

**Comment by realvorl** [comment]
Yeah, this is a bug 🪲

**Comment by realvorl** [comment]
OK @emunaelator it was an easy fix, did not do the whole PR review thing, because I am a `one man show` for the moment. Now when you press the Share Badge button the URL is complete and shareable. 

This commit: baee4c1
Allows me to link to a badge [`V30 seven`](https://realvorl.github.io/BadgeSVGen/?data=eyJ0ZXh0MSI6IlYzMCIsInRleHQyIjoic2V2ZW4iLCJ3aWR0aCI6NzQsImhlaWdodCI6MjAsImZvbnRTaXplIjoxMSwiaGludFNpemUiOjEyLCJmaWxsQ29sb3IxIjoiIzE5MzI1MiIsImZpbGxDb2xvcjIiOiIjMjA4YTBhIiwidGV4dENvbG9yMSI6IiNmZmZmZmYiLCJ0ZXh0Q29sb3IyIjoiI2ZmZmZmZiIsImRpdmlkZXJMaW5lIjozMn0=)  some nonsense thing I did the testing with ... 

Will close the this issue now.
BR.
